### ISSUE TITLE
install fails on windows when running python 2.7

### ISSUE THREAD

**Issue by j9ac9k** [stevenbedrick/bitweight#2]
Running `python setup.py install` results in a failure when running Python 2.7 on Windows systems.

```
python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to BitWeight.egg-info\requires.txt
writing BitWeight.egg-info\PKG-INFO
writing top-level names to BitWeight.egg-info\top_level.txt
writing dependency_links to BitWeight.egg-info\dependency_links.txt
reading manifest file 'BitWeight.egg-info\SOURCES.txt'
writing manifest file 'BitWeight.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'bitweight' extension
C:\Users\ogi\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Miniconda3\envs\py2\include -IC:\Miniconda3\envs\py2\PC /Tpbitweight.cpp /Fobuild\temp.win-amd64-2.7\Release\bitweight.obj -std=c++11
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
bitweight.cpp
c:\users\ogi\documents\github\bitweight-public\bitweight.h(45) : error C2146: syntax error : missing ';' before identifier 'T'
        c:\users\ogi\documents\github\bitweight-public\bitweight.h(78) : see reference to class template instantiation 'bitweight::BitWeightTpl<T>' being compiled
c:\users\ogi\documents\github\bitweight-public\bitweight.h(45) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ogi\documents\github\bitweight-public\bitweight.h(45) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ogi\documents\github\bitweight-public\bitweight.h(45) : error C2864: 'bitweight::BitWeightTpl<T>::big' : only static const integral data members can be initialized within a class
c:\users\ogi\documents\github\bitweight-public\bitweight.h(95) : error C2143: syntax error : missing ';' before '='
c:\users\ogi\documents\github\bitweight-public\bitweight.h(95) : error C2873: 'BitWeight' : symbol cannot be used in a using-declaration
c:\users\ogi\documents\github\bitweight-public\bitweight.h(95) : error C2513: 'int' : no variable declared before '='
bitweight.cpp(672) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(672) : error C2143: syntax error : missing ';' before '*'
bitweight.cpp(672) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
bitweight.cpp(672) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
bitweight.cpp(1024) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(1024) : error C2065: 'BitWeight' : undeclared identifier
bitweight.cpp(1024) : error C2065: '__pyx_t_7' : undeclared identifier
bitweight.cpp(1195) : error C2065: '__pyx_t_7' : undeclared identifier
bitweight.cpp(1195) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(1195) : error C2061: syntax error : identifier 'BitWeight'
bitweight.cpp(1197) : error C2065: '__pyx_t_7' : undeclared identifier
bitweight.cpp(1197) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(1197) : error C2061: syntax error : identifier 'BitWeight'
bitweight.cpp(1199) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1199) : error C2065: '__pyx_t_7' : undeclared identifier
bitweight.cpp(1255) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1304) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1304) : error C2227: left of '->real' must point to class/struct/union/generic type
bitweight.cpp(1367) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1367) : error C2227: left of '->+=' must point to class/struct/union/generic type
bitweight.cpp(1367) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1434) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1434) : error C2227: left of '->*=' must point to class/struct/union/generic type
bitweight.cpp(1434) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1501) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1501) : error C2227: left of '->/=' must point to class/struct/union/generic type
bitweight.cpp(1501) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1584) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1584) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(1584) : error C2061: syntax error : identifier 'BitWeight'
bitweight.cpp(1672) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1672) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(1672) : error C2061: syntax error : identifier 'BitWeight'
bitweight.cpp(1760) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1760) : error C2039: 'BitWeight' : is not a member of 'bitweight'
bitweight.cpp(1760) : error C2061: syntax error : identifier 'BitWeight'
bitweight.cpp(1849) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1849) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1881) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1881) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1912) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
bitweight.cpp(1912) : error C2039: 'ptr' : is not a member of '__pyx_obj_9bitweight_BitWeight'
        bitweight.cpp(670) : see declaration of '__pyx_obj_9bitweight_BitWeight'
error: command 'C:\\Users\\ogi\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```

can confirm that install works fine on Python 3.5 on Windows, as well as Python 2.7 and 3.5 on Windows Linux Subsystem.

**Comment by kylebgorman** [comment]
Looks like the compiler doesn't have support for C++11. Why this is
sensitive to Python versioning, I have no idea.

**Comment by j9ac9k** [comment]
Actually I missed a bit of (what could be) critical information.

On the first attempt to install, it prompted me to download the Visual C++ Compiler for Python 2.7

```
> python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to BitWeight.egg-info\requires.txt
writing BitWeight.egg-info\PKG-INFO
writing top-level names to BitWeight.egg-info\top_level.txt
writing dependency_links to BitWeight.egg-info\dependency_links.txt
reading manifest file 'BitWeight.egg-info\SOURCES.txt'
writing manifest file 'BitWeight.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'bitweight' extension
error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

Upon installing that, I got the error above.

**Comment by kylebgorman** [comment]
Hmm, strange. It looks like it's complaining about C++11 syntax use to me,
but I don't have access to a Windows machine, unfortunately, so I am going
to leave this to you to debug.

It's possible the code that Cython is generating is also just---bad?

**Comment by j9ac9k** [comment]
I'll mess with it, although I have a sneaking suspicion this might be a conda distribution of python thing (similar to the python bindings for openfst that wouldn't build on a conda distribution of Python on OS X, but built fine when installing with the system version of Python).
